#!/usr/bin/env bash
# devhost configure — render the inventory and variables from .env, wait for the
# host to answer over SSH, then run the Ansible playbook (and optionally the
# on-host verification suite).
#
# Usage:
#   scripts/configure.sh                  # provision the host over the bootstrap path
#   scripts/configure.sh --tailscale-only # after Tailscale works: drop the WAN SSH rule
#   scripts/configure.sh --tags tmux      # extra args pass through to ansible-playbook
#
# Idempotent: re-running the playbook changes nothing when nothing changed.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STATE="$ROOT/state/devhost.env"
[ -f "$ROOT/.env" ] && { set -a; . "$ROOT/.env"; set +a; }
[ -f "$STATE" ] || { echo "state/devhost.env not found — run scripts/provision.sh first" >&2; exit 1; }
# shellcheck disable=SC1090
. "$STATE"

SSH_KEY_PATH="${SSH_KEY_PATH:-$HOME/.ssh/id_ed25519}"
SSH_USER="${SSH_USER:-ubuntu}"
USE_TAILSCALE="${USE_TAILSCALE:-auto}"
SSH_WAIT_SECONDS="${SSH_WAIT_SECONDS:-300}"
TAILSCALE_ONLY=0
PASSTHRU=()

while [ $# -gt 0 ]; do
    case "$1" in
        --tailscale-only) TAILSCALE_ONLY=1; shift ;;
        *) PASSTHRU+=("$1"); shift ;;
    esac
done

green="\033[0;32m"; red="\033[0;31m"; yellow="\033[0;33m"; blue="\033[0;34m"; reset="\033[0m"
ok()   { printf "${green}ok${reset}   %s\n" "$1"; }
warn() { printf "${yellow}warn${reset} %s\n" "$1"; }
die()  { printf "${red}fail${reset} %s\n" "$1"; exit 1; }
step() { printf "\n${blue}==>${reset} %s\n" "$1"; }

ANSIBLE_DIR="$ROOT/ansible"
cd "$ANSIBLE_DIR"

# --- Decide the transport -------------------------------------------------
# Tailscale when we can find the node in the local tailnet; otherwise the
# public IP (which only works while the bootstrap SSH rule is open).
tailnet_name="$(tailscale status --json 2>/dev/null | DEVHOST_NAME="$DEVHOST_NAME" python3 -c '
import json, os, sys
want = os.environ["DEVHOST_NAME"].lower()
try:
    peers = json.load(sys.stdin).get("Peer") or {}
except Exception:
    sys.exit(0)
for peer in peers.values():
    if (peer.get("HostName") or "").lower() == want and (peer.get("Online") or False):
        print((peer.get("DNSName") or "").rstrip("."))
        break
' 2>/dev/null || true)"

transport="public"
host=""
if [ "$TAILSCALE_ONLY" = "1" ] || [ "$USE_TAILSCALE" = "1" ] || { [ "$USE_TAILSCALE" = "auto" ] && [ -n "$tailnet_name" ]; }; then
    [ -n "$tailnet_name" ] || die "no online tailnet node named '$DEVHOST_NAME'. Join this machine to Tailscale, or set USE_TAILSCALE=0 to use the public IP."
    transport="tailscale"
    host="$tailnet_name"
else
    host="$PUBLIC_IP"
    [ -n "$host" ] || die "no public IP recorded and no tailnet node found. Set PUBLIC_IP in state/devhost.env."
fi
step "Transport: $transport ($host)"

# --- Render inventory ----------------------------------------------------
step "Rendering ansible/inventory.ini"
cat > inventory.ini <<EOF
# Generated by scripts/configure.sh — edit .env, not this file.
[devhost]
$DEVHOST_NAME ansible_host=$host ansible_user=$SSH_USER ansible_ssh_private_key_file=$SSH_KEY_PATH

[devhost:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args=-o StrictHostKeyChecking=accept-new -o ConnectTimeout=10 -o UserKnownHostsFile=$HOME/.ssh/known_hosts
EOF
ok "inventory.ini -> $host"

# --- Render group_vars ---------------------------------------------------
step "Rendering group_vars"
# The bootstrap /32 is only needed while the host has no tailnet path. Once the
# transport is the tailnet, close the WAN rule — and name it for removal,
# because the firewall role adds rules but never deletes them.
if [ -z "${BOOTSTRAP_SSH_CIDR:-}" ]; then
    [ "$transport" = "public" ] && die "BOOTSTRAP_SSH_CIDR is empty in state/devhost.env, but the host is only reachable over the public IP. Re-run scripts/provision.sh first."
    wan_allow="[]"
    wan_allow_remove="[]"
elif [ "$TAILSCALE_ONLY" = "1" ] || [ "$transport" = "tailscale" ]; then
    wan_allow="[]"
    wan_allow_remove="[\"$BOOTSTRAP_SSH_CIDR\"]"
else
    wan_allow="[\"$BOOTSTRAP_SSH_CIDR\"]"
    wan_allow_remove="[]"
fi

cat > group_vars/all/local.yml <<EOF
---
# Generated by scripts/configure.sh — edit .env, not this file.
devhost_name: "$DEVHOST_NAME"
ssh_user: "$SSH_USER"
target_users:
  - "$SSH_USER"
ssh_wan_allow: $wan_allow
ssh_wan_allow_remove: $wan_allow_remove
expose_public_http: ${EXPOSE_PUBLIC_HTTP:-false}
expose_public_https: ${EXPOSE_PUBLIC_HTTPS:-false}
caddy_public_sites: ${CADDY_PUBLIC_SITES:-[]}
EOF
if [ "$wan_allow_remove" = "[]" ]; then
    ok "group_vars/all/local.yml (ssh_wan_allow: $wan_allow)"
else
    ok "group_vars/all/local.yml (ssh_wan_allow: $wan_allow, removing: $wan_allow_remove)"
fi

umask 077
cat > group_vars/all/secrets.yml <<EOF
---
# Generated by scripts/configure.sh — never commit this file.
tailscale_auth_key: "${TAILSCALE_AUTH_KEY:-}"
EOF
ok "group_vars/all/secrets.yml (mode 0600)"

# --- Wait for SSH --------------------------------------------------------
step "Waiting for SSH on $host"
deadline=$((SECONDS + SSH_WAIT_SECONDS))
attempt=0
until ssh -o BatchMode=yes -o StrictHostKeyChecking=accept-new -o ConnectTimeout=5 \
        -i "$SSH_KEY_PATH" "$SSH_USER@$host" true 2>/dev/null; do
    attempt=$((attempt + 1))
    [ "$SECONDS" -lt "$deadline" ] || die "SSH did not come up within ${SSH_WAIT_SECONDS}s. Check: the cloud NSG allows tcp/22 from $BOOTSTRAP_SSH_CIDR, and the instance is RUNNING."
    [ $((attempt % 6)) -eq 1 ] && warn "still waiting (${attempt} attempts, $((deadline - SECONDS))s left)"
    sleep 5
done
ok "SSH answered as $SSH_USER@$host"

# --- Run the playbook ----------------------------------------------------
if [ "$TAILSCALE_ONLY" = "1" ]; then
    step "Checking that Tailscale is up before locking the WAN path"
    remote_state="$(ssh -o BatchMode=yes -i "$SSH_KEY_PATH" "$SSH_USER@$host" \
        'tailscale status --json 2>/dev/null | python3 -c "import json,sys; print(json.load(sys.stdin).get(\"BackendState\",\"\"))"' 2>/dev/null || true)"
    [ "$remote_state" = "Running" ] || die "Tailscale on the host reports '$remote_state'. Finish the login first (run the URL the playbook printed), then re-run with --tailscale-only."
    ok "tailnet is up"
fi

step "Running the playbook"
ansible-playbook -i inventory.ini site.yml "${PASSTHRU[@]+"${PASSTHRU[@]}"}"
ok "playbook finished"

# --- Tailscale state -----------------------------------------------------
remote_state="$(ssh -o BatchMode=yes -i "$SSH_KEY_PATH" "$SSH_USER@$host" \
    'tailscale status --json 2>/dev/null | python3 -c "import json,sys; print(json.load(sys.stdin).get(\"BackendState\",\"\"))"' 2>/dev/null || true)"
if [ "$remote_state" = "Running" ]; then
    ok "Tailscale authenticated (transport: $transport)"
else
    warn "Tailscale is not authenticated yet (BackendState=${remote_state:-unknown})."
    warn "Ask the user to open the login URL, or run:"
    warn "  ssh $SSH_USER@$host sudo tailscale up --hostname=$DEVHOST_NAME --ssh --accept-dns=true"
    warn "Then re-run: scripts/configure.sh --tailscale-only"
fi

# --- Client SSH config ---------------------------------------------------
step "Client SSH config"
ssh_dir="$HOME/.ssh"
mkdir -p "$ssh_dir/sockets" && chmod 700 "$ssh_dir/sockets"
if grep -qE "^Host[[:space:]]+$DEVHOST_NAME\$" "$ssh_dir/config" 2>/dev/null; then
    ok "~/.ssh/config already has a '$DEVHOST_NAME' block"
else
    {
        echo
        sed -e "s|__DEVHOST__|$DEVHOST_NAME|g" \
            -e "s|__SSH_USER__|$SSH_USER|g" \
            -e "s|__SSH_KEY__|$SSH_KEY_PATH|g" \
            "$ROOT/ansible/files/ssh_config" > "$ssh_dir/config.devhost.tmp"
        # HostName: prefer the tailnet name; the public IP stops working once the
        # host is Tailscale-only.
        if [ -n "$tailnet_name" ]; then
            sed -i "s|__HOSTNAME__|$tailnet_name|g" "$ssh_dir/config.devhost.tmp"
        else
            sed -i "s|__HOSTNAME__|$PUBLIC_IP|g" "$ssh_dir/config.devhost.tmp"
        fi
        cat "$ssh_dir/config.devhost.tmp"
        rm -f "$ssh_dir/config.devhost.tmp"
    } >> "$ssh_dir/config"
    chmod 600 "$ssh_dir/config"
    ok "appended 'Host $DEVHOST_NAME' to ~/.ssh/config"
fi

step "Done"
if [ "$TAILSCALE_ONLY" = "1" ]; then
    ok "host is Tailscale-only; the WAN SSH rule is gone"
fi
ok "verify from here:  scripts/verify.sh"
ok "log in from here:  ssh $DEVHOST_NAME"
